/**
 * Shared atlas info for the billboard scenes (34, 35, 36).
 *
 * The atlas PNG is generated by `scripts/build-billboard-atlas.ts` and
 * committed at `lab/public/sprites/billboards/atlas.png`. Both BJS and Lite
 * scene paths fetch the same URL, so the atlas bytes are bit-exact identical
 * (no canvas2D float-rounding noise leaking into the parity diff).
 */
export const BILLBOARD_ATLAS_URL = "/sprites/billboards/atlas.png";

export const BILLBOARD_ATLAS_INFO = {
    widthPx: 192,
    heightPx: 64,
    cellWidthPx: 64,
    cellHeightPx: 64,
    columns: 3,
    rows: 1,
    /** 0 = glow disc, 1 = tree silhouette, 2 = flag/banner */
    frames: { glow: 0, tree: 1, flag: 2 } as const,
};
